const SET_LOADING_ACTION = 'SET_LOADING'
const SET_PRODUCT_ACTION = 'SET_PRODUCT_ACTION'
const SET_SELECTED_SIZE_ACTION = 'SET_SELECTED_SIZE_ACTION'
const SET_ERROR_ACTION = 'SET_ERROR_ACTION'

const detailsConsts = {
    SET_LOADING_ACTION,
    SET_PRODUCT_ACTION,
    SET_SELECTED_SIZE_ACTION,
    SET_ERROR_ACTION
}
export default detailsConsts